<?php

require_once(__DIR__ . "/lib/LagoonLogger.php");

/**
 * implements hook_watchdog()
 */
function lagoon_logs_watchdog(array $log_entry) {
  if (!class_exists('\Monolog\Logger')) {
    LagoonLogger::logWatchdogFallbackMessage('Lagoon Logs needs the Monolog library installed to run');
    return;
  }

  if($log_entry['type'] != LagoonLogger::LAGOON_LOGGER_WATCHDOG_FALLBACK_IDENTIFIER) {
    print($log_entry['type']);
    $logger = LagoonLogger::getLogger(variable_get('LAGOON_LOGS_HOST', '172.17.0.1'),
      variable_get('LAGOON_LOGS_PORT', '5140'),
      variable_get('LAGOON_LOGS_IDENTIFIER', 'DRUPAL'));
    $logger->log($log_entry);
  }
}